name: Koyeb Login

on:
  schedule:
    - cron: '0 0 * * 1' # 每周一 UTC 时间 0 点运行
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2

      - name: Login to Koyeb
        env:
          KOYEB_API_KEYS: ${{ secrets.KOYEB_API_KEYS }}
        run: |
          mkdir -p ~/.koyeb
          IFS=',' read -r -a api_keys <<< "$KOYEB_API_KEYS"
          for api_key in "${api_keys[@]}"; do
            cat <<EOF > ~/.koyeb.yaml
api_key: $api_key
EOF
            # Verify the login
            koyeb -k $api_key apps list
          done
