name: Weekly Koyeb Login

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日0点运行
  workflow_dispatch:  # 手动触发工作流

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Koyeb login script
      env:
        KOYEB_API_TOKENS: ${{ secrets.KOYEB_API_TOKENS }}  # 在 GitHub secrets 中设置你的多个 Koyeb API tokens，以逗号分隔
      run: python3 login_to_koyeb.py
