name: Login to Koyeb
on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install && npx playwright install
             
      - name: Login to Koyeb
        run: node login.js
        env:
          USERNAMES: ${{ secrets.USERNAMES }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
