name: Weekly Login to Koyeb
on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日的 00:00 运行
  workflow_dispatch:
  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Koyeb for multiple accounts
        run: |
          IFS=',' read -ra TOKENS <<< "${{ secrets.KOYEB_TOKENS }}"
          for TOKEN in "${TOKENS[@]}"; do
            echo "Logging in with token: $TOKEN"
            echo "::add-mask::$TOKEN"
            echo $TOKEN | koyeb login
          done
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKENS }}
        uses: koyeb-community/install-koyeb-cli@v2
