name: Weekly Login to Koyeb
on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2

      - name: Login to Koyeb for multiple accounts
        run: |
          IFS=',' read -ra TOKENS <<< "${{ secrets.KOYEB_TOKENS }}"
          for TOKEN in "${TOKENS[@]}"; do
            echo "Logging in with token: $TOKEN"
            echo "::add-mask::$TOKEN"
            koyeb login --token $TOKEN
          done
