name: Weekly Login to Koyeb
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Koyeb for multiple accounts
        run: |
          IFS=',' read -ra TOKENS <<< "${{ secrets.KOYEB_TOKENS }}"
          for TOKEN in "${TOKENS[@]}"; do
            echo "Installing Koyeb CLI and logging in with token: $TOKEN"
            echo "::add-mask::$TOKEN"
            echo $TOKEN | koyeb login
          done
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_TOKENS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
